"""offipy 高层 API 类型 stub（由 scripts/gen_api_stub.py 生成，勿手改）。

本地直连 Excel()/Word()/Ppt() 与远程 RemoteExcel()/RemoteWord()/RemotePpt()
的显式 op 签名，供 mypy/IDE。破坏性 op 传输层参数：direct 只走 follow_active，
remote 额外走 expected_target（与 MCP/CLI 同策略）。doc_id 缺省走当前活动文档。
"""

from typing import Any

class Excel:
    def __init__(self, visible: bool = True) -> None: ...
    def __enter__(self) -> Excel: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

    def new_book(self) -> str: ...
    def open_book(self, path: str) -> str: ...
    def close_book(self, save: bool = True, doc_id: str | None = None, *, follow_active: bool = False) -> str | None: ...
    def save(self, path: str | None = None, overwrite: bool = False, doc_id: str | None = None, *, follow_active: bool = False) -> str: ...
    def save_pdf(self, path: str, overwrite: bool = False, doc_id: str | None = None) -> None: ...
    def add_sheet(self, name: str, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def set_cell(self, sheet: Any, cell: str, value: Any, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def get_cell(self, sheet: Any, cell: str, doc_id: str | None = None) -> Any: ...
    def set_range(self, sheet: Any, range_addr: str, values: Any, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def set_col_width(self, sheet: Any, col: Any, width: float, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def format_cell(self, sheet: Any, cell: str, bold: bool | None = None, size: float | None = None, italic: bool | None = None, bg: str | None = None, fg: str | None = None, align: int | None = None, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def merge_cells(self, sheet: Any, range_addr: str, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def unmerge_cells(self, sheet: Any, range_addr: str, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def set_border(self, sheet: Any, range_addr: str, side: str = 'all', style: str = 'continuous', weight: str = 'thin', color: str | None = None, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def freeze_panes(self, sheet: Any, rows: int = 0, cols: int = 0, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def page_setup(self, sheet: Any, orientation: str | None = None, paper: str | None = None, fit_to_pages_wide: int | None = None, fit_to_pages_tall: int | None = None, margins: Any = None, print_area: str | None = None, center_horizontally: bool | None = None, center_vertically: bool | None = None, print_titles_rows: str | None = None, print_titles_cols: str | None = None, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def add_conditional_format(self, sheet: Any, range_addr: str, rule: str, operator: str | None = None, value: Any = None, value2: Any = None, bg: str | None = None, fg: str | None = None, min_color: str | None = None, max_color: str | None = None, mid_color: str | None = None, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def set_row_height(self, sheet: Any, row: int, height: float, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def set_number_format(self, sheet: Any, range_addr: str, fmt: str, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def autofit(self, sheet: Any, range_addr: str | None = None, columns: bool = True, rows: bool = True, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def read_range(self, sheet: Any, range_addr: str, doc_id: str | None = None) -> list: ...
    def activate(self, doc_id: str | None) -> None: ...
    def list_docs(self) -> dict: ...
    def get_target(self, doc_id: str | None = None) -> dict: ...
    def quit(self, force: bool = False) -> None: ...

class RemoteExcel:
    def __init__(self, base_url: str | None = None) -> None: ...
    def __enter__(self) -> RemoteExcel: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

    def new_book(self) -> str: ...
    def open_book(self, path: str) -> str: ...
    def close_book(self, save: bool = True, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> str | None: ...
    def save(self, path: str | None = None, overwrite: bool = False, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> str: ...
    def save_pdf(self, path: str, overwrite: bool = False, doc_id: str | None = None) -> None: ...
    def add_sheet(self, name: str, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def set_cell(self, sheet: Any, cell: str, value: Any, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def get_cell(self, sheet: Any, cell: str, doc_id: str | None = None) -> Any: ...
    def set_range(self, sheet: Any, range_addr: str, values: Any, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def set_col_width(self, sheet: Any, col: Any, width: float, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def format_cell(self, sheet: Any, cell: str, bold: bool | None = None, size: float | None = None, italic: bool | None = None, bg: str | None = None, fg: str | None = None, align: int | None = None, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def merge_cells(self, sheet: Any, range_addr: str, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def unmerge_cells(self, sheet: Any, range_addr: str, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def set_border(self, sheet: Any, range_addr: str, side: str = 'all', style: str = 'continuous', weight: str = 'thin', color: str | None = None, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def freeze_panes(self, sheet: Any, rows: int = 0, cols: int = 0, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def page_setup(self, sheet: Any, orientation: str | None = None, paper: str | None = None, fit_to_pages_wide: int | None = None, fit_to_pages_tall: int | None = None, margins: Any = None, print_area: str | None = None, center_horizontally: bool | None = None, center_vertically: bool | None = None, print_titles_rows: str | None = None, print_titles_cols: str | None = None, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def add_conditional_format(self, sheet: Any, range_addr: str, rule: str, operator: str | None = None, value: Any = None, value2: Any = None, bg: str | None = None, fg: str | None = None, min_color: str | None = None, max_color: str | None = None, mid_color: str | None = None, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def set_row_height(self, sheet: Any, row: int, height: float, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def set_number_format(self, sheet: Any, range_addr: str, fmt: str, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def autofit(self, sheet: Any, range_addr: str | None = None, columns: bool = True, rows: bool = True, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def read_range(self, sheet: Any, range_addr: str, doc_id: str | None = None) -> list: ...
    def activate(self, doc_id: str | None) -> None: ...
    def list_docs(self) -> dict: ...
    def get_target(self, doc_id: str | None = None) -> dict: ...
    def quit(self, force: bool = False) -> None: ...

class Word:
    def __init__(self, visible: bool = True) -> None: ...
    def __enter__(self) -> Word: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

    def new_doc(self) -> str: ...
    def open_doc(self, path: str) -> str: ...
    def close_doc(self, save: bool = True, doc_id: str | None = None, *, follow_active: bool = False) -> str | None: ...
    def save(self, path: str | None = None, overwrite: bool = False, doc_id: str | None = None, *, follow_active: bool = False) -> str: ...
    def save_pdf(self, path: str, overwrite: bool = False, doc_id: str | None = None) -> None: ...
    def write(self, text: str, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def write_line(self, text: str, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def add_heading(self, text: str, level: int = 1, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def add_table(self, rows: int, cols: int, doc_id: str | None = None, *, follow_active: bool = False) -> int: ...
    def set_table_cell(self, table_idx: int, row: int, col: int, text: str, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def format_text(self, paragraph: int, bold: bool | None = None, italic: bool | None = None, size: float | None = None, name: str | None = None, color: str | None = None, underline: str | None = None, highlight: str | None = None, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def format_paragraph(self, paragraph: int, alignment: str | None = None, line_spacing: str | None = None, space_before: float | None = None, space_after: float | None = None, left_indent: float | None = None, first_line_indent: float | None = None, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def set_header_text(self, text: str, section: int = 1, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def set_footer_text(self, text: str, section: int = 1, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def add_page_number(self, alignment: str = 'right', color: str | None = None, size: float | None = None, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def page_setup(self, orientation: str | None = None, paper: str | None = None, left_margin: float | None = None, right_margin: float | None = None, top_margin: float | None = None, bottom_margin: float | None = None, gutter: float | None = None, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def insert_toc(self, levels: int = 3, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def update_toc(self, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def add_list(self, lines: list, style: str = 'bullet', doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def merge_table_cells(self, table_idx: int, start_row: int, start_col: int, end_row: int, end_col: int, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def set_table_border(self, table_idx: int, style: str = 'single', weight: str | None = None, color: str | None = None, sides: str | None = None, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def set_table_col_width(self, table_idx: int, col: int, width: float, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def set_table_row_height(self, table_idx: int, row: int, height: float, rule: str = 'at_least', doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def autofit_table(self, table_idx: int, behavior: str = 'content', doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def find_replace(self, find: str, replace: str, match_case: bool = False, whole_word: bool = False, replace_all: bool = True, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def insert_image(self, path: str, width: float | None = None, height: float | None = None, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def insert_page_break(self, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def read_doc_text(self, doc_id: str | None = None) -> str: ...
    def activate(self, doc_id: str | None) -> None: ...
    def list_docs(self) -> dict: ...
    def get_target(self, doc_id: str | None = None) -> dict: ...
    def quit(self, force: bool = False) -> None: ...

class RemoteWord:
    def __init__(self, base_url: str | None = None) -> None: ...
    def __enter__(self) -> RemoteWord: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

    def new_doc(self) -> str: ...
    def open_doc(self, path: str) -> str: ...
    def close_doc(self, save: bool = True, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> str | None: ...
    def save(self, path: str | None = None, overwrite: bool = False, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> str: ...
    def save_pdf(self, path: str, overwrite: bool = False, doc_id: str | None = None) -> None: ...
    def write(self, text: str, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def write_line(self, text: str, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def add_heading(self, text: str, level: int = 1, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def add_table(self, rows: int, cols: int, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> int: ...
    def set_table_cell(self, table_idx: int, row: int, col: int, text: str, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def format_text(self, paragraph: int, bold: bool | None = None, italic: bool | None = None, size: float | None = None, name: str | None = None, color: str | None = None, underline: str | None = None, highlight: str | None = None, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def format_paragraph(self, paragraph: int, alignment: str | None = None, line_spacing: str | None = None, space_before: float | None = None, space_after: float | None = None, left_indent: float | None = None, first_line_indent: float | None = None, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def set_header_text(self, text: str, section: int = 1, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def set_footer_text(self, text: str, section: int = 1, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def add_page_number(self, alignment: str = 'right', color: str | None = None, size: float | None = None, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def page_setup(self, orientation: str | None = None, paper: str | None = None, left_margin: float | None = None, right_margin: float | None = None, top_margin: float | None = None, bottom_margin: float | None = None, gutter: float | None = None, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def insert_toc(self, levels: int = 3, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def update_toc(self, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def add_list(self, lines: list, style: str = 'bullet', doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def merge_table_cells(self, table_idx: int, start_row: int, start_col: int, end_row: int, end_col: int, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def set_table_border(self, table_idx: int, style: str = 'single', weight: str | None = None, color: str | None = None, sides: str | None = None, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def set_table_col_width(self, table_idx: int, col: int, width: float, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def set_table_row_height(self, table_idx: int, row: int, height: float, rule: str = 'at_least', doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def autofit_table(self, table_idx: int, behavior: str = 'content', doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def find_replace(self, find: str, replace: str, match_case: bool = False, whole_word: bool = False, replace_all: bool = True, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def insert_image(self, path: str, width: float | None = None, height: float | None = None, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def insert_page_break(self, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def read_doc_text(self, doc_id: str | None = None) -> str: ...
    def activate(self, doc_id: str | None) -> None: ...
    def list_docs(self) -> dict: ...
    def get_target(self, doc_id: str | None = None) -> dict: ...
    def quit(self, force: bool = False) -> None: ...

class Ppt:
    def __init__(self, visible: bool = True) -> None: ...
    def __enter__(self) -> Ppt: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

    def new_pres(self) -> str: ...
    def open_pres(self, path: str) -> str: ...
    def save(self, path: str | None = None, overwrite: bool = False, doc_id: str | None = None, *, follow_active: bool = False) -> str: ...
    def save_pdf(self, path: str, overwrite: bool = False, doc_id: str | None = None) -> None: ...
    def export_slides(self, out_dir: str, width: int = 1920, height: int = 1080, doc_id: str | None = None) -> list: ...
    def add_slide(self, layout: int = 2, doc_id: str | None = None, *, follow_active: bool = False) -> int: ...
    def set_title(self, slide_idx: int, text: str, doc_id: str | None = None, *, follow_active: bool = False) -> int: ...
    def set_body(self, slide_idx: int, lines: Any, doc_id: str | None = None, *, follow_active: bool = False) -> int: ...
    def set_notes(self, slide_idx: int, text: str, doc_id: str | None = None, *, follow_active: bool = False) -> int: ...
    def add_textbox(self, slide_idx: int, left: float, top: float, width: float, height: float, text: str, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def add_picture(self, slide_idx: int, path: str, left: float, top: float, width: float, height: float, doc_id: str | None = None, *, follow_active: bool = False) -> None: ...
    def read_slide_texts(self, doc_id: str | None = None) -> list: ...
    def activate(self, doc_id: str | None) -> None: ...
    def list_docs(self) -> dict: ...
    def get_target(self, doc_id: str | None = None) -> dict: ...
    def quit(self, force: bool = False) -> None: ...

class RemotePpt:
    def __init__(self, base_url: str | None = None) -> None: ...
    def __enter__(self) -> RemotePpt: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

    def new_pres(self) -> str: ...
    def open_pres(self, path: str) -> str: ...
    def save(self, path: str | None = None, overwrite: bool = False, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> str: ...
    def save_pdf(self, path: str, overwrite: bool = False, doc_id: str | None = None) -> None: ...
    def export_slides(self, out_dir: str, width: int = 1920, height: int = 1080, doc_id: str | None = None) -> list: ...
    def add_slide(self, layout: int = 2, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> int: ...
    def set_title(self, slide_idx: int, text: str, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> int: ...
    def set_body(self, slide_idx: int, lines: Any, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> int: ...
    def set_notes(self, slide_idx: int, text: str, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> int: ...
    def add_textbox(self, slide_idx: int, left: float, top: float, width: float, height: float, text: str, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def add_picture(self, slide_idx: int, path: str, left: float, top: float, width: float, height: float, doc_id: str | None = None, *, expected_target: dict | None = None, follow_active: bool = False) -> None: ...
    def read_slide_texts(self, doc_id: str | None = None) -> list: ...
    def activate(self, doc_id: str | None) -> None: ...
    def list_docs(self) -> dict: ...
    def get_target(self, doc_id: str | None = None) -> dict: ...
    def quit(self, force: bool = False) -> None: ...

def op(app: str, op_name: str, **kw: Any) -> Any: ...
